### PR TITLE
Fixing package security issues

### PR DESCRIPTION
**Pull request by ryandberger**
Updating dependencies to github security recommended versions.

### CODE REVIEW

**Comment by zburke** [comment]
How did you make these changes to the `yarn.lock` file? I face this issue in other platform repositories where the vulnerable libraries are not direct dependencies of the platforms, and it isn't clear if/how to get yarn to update these transitive dependencies.

**Comment by ryandberger** [comment]
> How did you make these changes to the `yarn.lock` file? I face this issue in other platform repositories where the vulnerable libraries are not direct dependencies of the platforms, and it isn't clear if/how to get yarn to update these transitive dependencies.

I handled this case by manually deleting each entry from the `yarn.lock` file per these instructions: https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563.

I also see that yarn has this available as a newer feature: https://yarnpkg.com/lang/en/docs/selective-version-resolutions. Haven't tried it yet, but it sounds like it could be a cleaner way to handle these issues.

**Comment by doytch** [comment]
So...few things:

- We started using `snapshot` as our "dev" branch when `platform-complete` started using `platform-erm` as a bit of a "dependency" for itself. `platform-complete` _stopped_ using this as a dependency a few months ago but the latest version of the code is still in `snapshot`.
- Soooo, can you run this PR against `snapshot` for now?
- (I am planning on shifting to using `master` in the next couple of weeks since `platform-complete` no longer uses this repo directly.)
- (As part of that, I'll actually be deleting the `yarn.lock` file in this repo. Again, that's something that's dragged on because of the whole platform-complete-started-using-this-and-then-stopped back-and-forth.)

**Comment by ryandberger** [comment]
> So...few things:
> 
> * We started using `snapshot` as our "dev" branch when `platform-complete` started using `platform-erm` as a bit of a "dependency" for itself. `platform-complete` _stopped_ using this as a dependency a few months ago but the latest version of the code is still in `snapshot`.
> * Soooo, can you run this PR against `snapshot` for now?
> * (I am planning on shifting to using `master` in the next couple of weeks since `platform-complete` no longer uses this repo directly. So I'll be merging `snapshot` into `master` soon.)
> * (As part of that, I'll actually be deleting the `yarn.lock` file in this repo. Again, that's something that's dragged on because of the whole platform-complete-started-using-this-and-then-stopped back-and-forth.)

Since there are package.json conflicts with what I did with master vs. what's in snapshot. I'm going to close this PR and open a new one after re-running against snapshot.

**Pull request closed without merging**
